name: Build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build for Linux x64
      run: dotnet publish -c Release -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:PublishTrimmed=true -r linux-x64
    - name: Build for Windows x64
      run: dotnet publish -c Release -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:PublishTrimmed=true -r win-x64
    - uses: actions/upload-artifact@v2
      with:
        name: SecretAdmin Linux x64
        path: SecretAdmin/bin/Release/net5.0/linux-x64/publish/SecretAdmin
    - uses: actions/upload-artifact@v2
      with:
        name: SecretAdmin Windows x64
        path: SecretAdmin/bin/Release/net5.0/win-x64/publish/SecretAdmin.exe
